site_name: synth-pdb
site_url: https://elkins-lab.github.io/synth-pdb
repo_url: https://github.com/elkins/synth-pdb
repo_name: elkins/synth-pdb
site_description: High-Performance Protein Structure Generator for AI/ML and Education
site_author: George Elkins
copyright: Copyright &copy; 2026 George Elkins

extra:
  version: v1.39.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elkins/synth-pdb
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/synth-pdb/

# Extra CSS/JS
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
