import numpy as np

from synth_pdb.generator import generate_pdb_content
from synth_pdb.validator import PDBValidator


def test_valine_chi1_distribution() -> None:
    """
    Validate that Valine chi1 angles generated by synth-pdb follow the
    backbone-dependent rotamer distribution (Dunbrack library).

    Scientific Evidence:
    For a generic backbone (not helix/sheet), Valine chi1 should have
    peaks at ~+60 (g+), ~180 (t), and ~-60 (g-). The 'trans' (180)
    conformation is usually the most favorable.

    We generate 50 Valines and check if we see at least two distinct
    rotamer populations.
    """
    seq = "V" * 50
    # Use random rotamers and random backbone to see the distribution
    pdb_content = generate_pdb_content(
        sequence_str=seq, conformation="random", optimize_sidechains=False
    )
    validator = PDBValidator(pdb_content)

    chi_angles_list = []
    for _chain_id, residues in validator.grouped_atoms.items():
        for _res_num, atoms in residues.items():
            if atoms.get("CA") and atoms["CA"]["residue_name"] == "VAL":
                # Calculate Chi1: N, CA, CB, CG1
                if all(k in atoms for k in ["N", "CA", "CB", "CG1"]):
                    coords = [atoms[k]["coords"] for k in ["N", "CA", "CB", "CG1"]]
                    chi1 = validator._calculate_dihedral_angle(*coords)
                    chi_angles_list.append(chi1)

    # Map to [-180, 180]
    chi_angles = np.array(chi_angles_list)

    # Valine rotamers (approximate centers):
    # m (minus): -60
    # p (plus):  +60
    # t (trans): 180

    m_count = int(np.sum((chi_angles > -100) & (chi_angles < -20)))
    p_count = int(np.sum((chi_angles > 20) & (chi_angles < 100)))
    t_count = int(np.sum((chi_angles > 140) | (chi_angles < -140)))

    total = len(chi_angles)
    print(f"\nValine Chi1 Stats (n={total}):")
    print(f"  g- (-60): {m_count} ({m_count/total:.1%})")
    print(f"  g+ (+60): {p_count} ({p_count/total:.1%})")
    print(f"  t  (180): {t_count} ({t_count/total:.1%})")

    # Assert that we didn't just get a single flat distribution at 0
    # and that most residues fall into one of the three clusters.
    assert (m_count + p_count + t_count) > (
        0.8 * total
    ), "Too many Valines in non-rotameric conformations"
    # Ensure diversity - at least 2 categories should be populated
    populated = sum(1 for c in [m_count, p_count, t_count] if c > 0)
    assert (
        populated >= 2
    ), f"Valine rotamers are not diverse enough (only {populated} categories populated)"
